
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author MyBook Hype AMD
 */
public class FrameTugas2KonversiSuhu extends javax.swing.JFrame {

    private boolean buttonKonversiKlik = false;

    /**
     * Creates new form FrameKonversiSuhu
     */
    public FrameTugas2KonversiSuhu() {
        initComponents();
        setTitle("Aplikasi Konversi Suhu");

        ItemListener listenerOtomatis = e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                hasilKonversiOtomatis();
            }
        };
        //Itemlistener disemua radio button
        rbtnCelcius.addItemListener(listenerOtomatis);
        rbtnFahrenheit.addItemListener(listenerOtomatis);
        rbtnKelvin.addItemListener(listenerOtomatis);
        rbtnReamur.addItemListener(listenerOtomatis);
        cbSatuan.addItemListener(listenerOtomatis);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelInput = new javax.swing.JLabel();
        labelDari = new javax.swing.JLabel();
        labelKe = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        cbSatuan = new javax.swing.JComboBox<>();
        rbtnCelcius = new javax.swing.JRadioButton();
        rbtnFahrenheit = new javax.swing.JRadioButton();
        rbtnReamur = new javax.swing.JRadioButton();
        rbtnKelvin = new javax.swing.JRadioButton();
        btnKonversi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelHasil = new javax.swing.JLabel();
        labelOutput = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        labelJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul.setText("APLIKASI KONVERSI SUHU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelJudul)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelInput.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labelInput.setText("Input Nilai Suhu :");

        labelDari.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labelDari.setText("Konversi Dari :");

        labelKe.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labelKe.setText("Konversi Ke :");

        txtInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInputFocusGained(evt);
            }
        });
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });

        cbSatuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Reamur", "Fahrenheit", "Kelvin" }));

        buttonGroup1.add(rbtnCelcius);
        rbtnCelcius.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnCelcius.setText("Celcius");
        rbtnCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCelciusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnFahrenheit);
        rbtnFahrenheit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnFahrenheit.setText("Fahrenheit");

        buttonGroup1.add(rbtnReamur);
        rbtnReamur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnReamur.setText("Reamur");

        buttonGroup1.add(rbtnKelvin);
        rbtnKelvin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbtnKelvin.setText("Kelvin");

        btnKonversi.setBackground(new java.awt.Color(153, 204, 255));
        btnKonversi.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelKe))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnReamur, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtInput)
                                .addComponent(cbSatuan, 0, 174, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDari))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKe)
                    .addComponent(rbtnCelcius)
                    .addComponent(rbtnFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnReamur)
                    .addComponent(rbtnKelvin))
                .addGap(18, 18, 18)
                .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelHasil.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labelHasil.setText("Hasil Konversi :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnReset.setBackground(new java.awt.Color(153, 204, 255));
        btnReset.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(153, 204, 255));
        btnKeluar.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCelciusActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        try {
            buttonKonversiKlik = true;
            double input = Double.parseDouble(txtInput.getText());
            String dari = cbSatuan.getSelectedItem().toString();
            double hasil = 0;
            String satuanHasil = "";

            // Menentukan tujuan konversi
            if (rbtnCelcius.isSelected()) {
                satuanHasil = "°C";
                if (dari.equals("Celcius")) {
                    hasil = input;
                } else if (dari.equals("Fahrenheit")) {
                    hasil = (input - 32) * 5 / 9;
                } else if (dari.equals("Reamur")) {
                    hasil = input * 5 / 4;
                } else if (dari.equals("Kelvin")) {
                    hasil = input - 273.15;
                }

            } else if (rbtnFahrenheit.isSelected()) {
                satuanHasil = "°F";
                if (dari.equals("Celcius")) {
                    hasil = (input * 9 / 5) + 32;
                } else if (dari.equals("Fahrenheit")) {
                    hasil = input;
                } else if (dari.equals("Reamur")) {
                    hasil = (input * 9 / 4) + 32;
                } else if (dari.equals("Kelvin")) {
                    hasil = (input - 273.15) * 9 / 5 + 32;
                }

            } else if (rbtnReamur.isSelected()) {
                satuanHasil = "°R";
                if (dari.equals("Celcius")) {
                    hasil = input * 4 / 5;
                } else if (dari.equals("Fahrenheit")) {
                    hasil = (input - 32) * 4 / 9;
                } else if (dari.equals("Reamur")) {
                    hasil = input;
                } else if (dari.equals("Kelvin")) {
                    hasil = (input - 273.15) * 4 / 5;
                }

            } else if (rbtnKelvin.isSelected()) {
                satuanHasil = "K";
                if (dari.equals("Celcius")) {
                    hasil = input + 273.15;
                } else if (dari.equals("Fahrenheit")) {
                    hasil = (input - 32) * 5 / 9 + 273.15;
                } else if (dari.equals("Reamur")) {
                    hasil = (input * 5 / 4) + 273.15;
                } else if (dari.equals("Kelvin")) {
                    hasil = input;
                }
            }

            // Tampilkan hasil
            labelOutput.setText(String.format("%.2f %s", hasil, satuanHasil));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInputFocusGained
        txtInput.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputFocusGained

    private void hasilKonversiOtomatis() {
        if (!buttonKonversiKlik) {
            return; // ❌ Belum klik hasil, jangan konversi dulu
        }
        if (!txtInput.getText().isEmpty()
                && (rbtnCelcius.isSelected() || rbtnFahrenheit.isSelected()
                || rbtnKelvin.isSelected() || rbtnReamur.isSelected())) {
            btnKonversiActionPerformed(null);
        }
    }

    private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Input tidak valid! Masukkan hanya angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputKeyTyped

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtInput.setText("");
        txtInput.requestFocus();
        buttonGroup1.clearSelection();
        cbSatuan.setSelectedIndex(0);
        labelOutput.setText(""); 
        buttonKonversiKlik = false;// TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased

    }//GEN-LAST:event_txtInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTugas2KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTugas2KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTugas2KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTugas2KonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTugas2KonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSatuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelDari;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelInput;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelKe;
    private javax.swing.JLabel labelOutput;
    private javax.swing.JRadioButton rbtnCelcius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JRadioButton rbtnKelvin;
    private javax.swing.JRadioButton rbtnReamur;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables

}
